### ISSUE TITLE
MultiTextField Ribbon

### ISSUE THREAD

**Issue by ViktorHofer** [Kaldeera/ng-SharePoint#32]
Hi,

currently a multitextfield with insert html and Images enabled does not invoke the default SharePoint ribbon at the top. Is it possible to use the native ribbon with the custom directives in this framework?

Thanks

**Comment by PauCodina** [comment]
Hi Viktor,

The framework does not generate SharePoint ribbon for multitextfields. If you puts a form into a custom page, the ribbon does not appears.

Instead of this, if you customize the standard list item form with ng-sharepoint, the framework uses the ribbon buttons and it works well.

Regards,
Pau
